# url_summary_plugin - 自动生成的配置文件
# 自动检测消息中的网址并发送内容摘要

[config_version]


# 通用设置
[general]

# 是否启用插件
enabled = true

# 是否在群聊启用
enable_group = true

# 是否在私聊启用
enable_private = true


# HTTP请求设置
[http]

# 请求超时时间(秒)
timeout = 10

# HTTP请求使用的User-Agent
user_agent = "Mozilla/5.0 (compatible; MaiBot-URL-Summary/2.0)"

# 最大重试次数
max_retries = 3

# HTTP请求所用的代理地址，如 http://127.0.0.1:7890
proxy = "http://127.0.0.1:7890"

# 最大重定向次数
max_redirects = 5

# 最大响应大小(字节)，默认10MB
max_response_size = 10485760


# 内容处理设置
[processing]

# 摘要最大长度
max_length = 600

# 是否包含标题
include_title = true

# 最小内容长度
min_content_length = 100

# 相关页面最多抓取数量
max_subpage = 3

# 相关页面摘要最大长度
subpage_length = 200

# 是否抓取站内相关页面摘要
enable_related_pages = true

# 摘要生成方式，可选 llm（智能摘要）、sentence（按句截断）、plain（原样截断）
summary_mode = "llm"

# LLM摘要时采用的模型配置key，例如：utils_small, replyer_1, replyer_2
llm_config_key = "replyer_1"


# 缓存设置
[cache]

# 防重复缓存时间(秒)
cache_ttl = 600

# URL摘要缓存时间(秒)
url_cache_ttl = 3600


# 安全设置
[security]

# 是否启用安全检查
enable_security_check = true

# 是否允许访问内网IP
allow_private_ip = false

# 禁止访问的主机列表
blocked_hosts = ['localhost', '127.0.0.1', '0.0.0.0', '::1', '169.254.169.254']

# 禁止访问的端口列表
blocked_ports = [22, 23, 135, 139, 445, 3389]

# 允许的URL协议
allowed_schemes = ['http', 'https']

# 最大URL长度
max_url_length = 2048

# 是否进行DNS解析检查
enable_dns_check = true

# DNS解析超时时间(秒)
dns_timeout = 5


